In [2]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv('/content/drive/MyDrive/AIML/trumptweets_small.csv', encoding="ISO-8859-1")
df.head()

,id,link,content,date,retweets,favorites,mentions,hashtags,geo
0,1698308935,https://twitter.com/realDonaldTrump/status/169...,Be sure to tune in and watch Donald Trump on L...,2009-05-04 20:54:25,500,868,NaN,NaN,NaN
1,1701461182,https://twitter.com/realDonaldTrump/status/170...,Donald Trump will be appearing on The View tom...,2009-05-05 03:00:10,33,273,NaN,NaN,NaN
2,1737479987,https://twitter.com/realDonaldTrump/status/173...,Donald Trump reads Top Ten Financial Tips on L...,2009-05-08 15:38:08,12,18,NaN,NaN,NaN
3,1741160716,https://twitter.com/realDonaldTrump/status/174...,New Blog Post: Celebrity Apprentice Finale and...,2009-05-08 22:40:15,11,24,NaN,NaN,NaN
4,1773561338,https://twitter.com/realDonaldTrump/status/177...,"""My persona will never be that of a wallflower...",2009-05-12 16:07:28,1399,1965,NaN,NaN,NaN

In [4]:
data_text = df["content"].dropna()

In [5]:
data_text[11]

'"We win in our lives by having a champion\'s view of each moment." --Donald J. Trump http://tinyurl.com/pqpfvm'

**Cleaning Functions**

In [6]:
import re
def remove_urls(text):
  """
  This function will try to remove URL present in out dataset and replace it with space using regex library.
  Input Args:
  text: strings of text that may contain URLs.
  Output Args:
  text: URLs replaces with text
  """
  url_pattern = re.compile(r'https?://\S+|www\.\S+')
  return url_pattern.sub(r'', text)

In [7]:
def remove_emoji(string):
  """
  This function will replace the emoji in string with whitespace
  """
  emoji_pattern = re.compile("["
                           u"\U0001F600-\U0001F64F"  # emoticons
                           u"\U0001F300-\U0001F5FF"  # symbols & pictographs
                           u"\U0001F680-\U0001F6FF"  # transport & map symbols
                           u"\U0001F1E0-\U0001F1FF"  # flags (iOS)
                           u"\U00002702-\U000027B0"
                           u"\U000024C2-\U0001F251"
                           "]+", flags=re.UNICODE)
  return emoji_pattern.sub(r' ', string)

In [8]:
def removeunwanted_characters(document):
  """
  This function will remove all the unwanted characters from the input dataset.
  Input Args:
  documet: A text data to be cleaned.
  Return:
  A cleaned document.
  """
  # remove user mentions
  document = re.sub("@[A-Za-z0-9_]+"," ", document)
  # remove hashtags
  document = re.sub("#[A-Za-z0-9_]+","", document)
  # remove punctuation
  document = re.sub("[^0-9A-Za-z ]", "" , document)
  #remove emojis
  document = remove_emoji(document)
  # remove double spaces
  document = document.replace('  ',"")
  return document.strip()

In [9]:
def lower_order(text):
  """
  This function converts all the text in input text to lower order.
  Input Args:
  token_text : input text.
  Returns:
  small_order_text : text converted to small/lower order.
  """
  small_order_text = text.lower()
  return small_order_text

# Test:
sample_text = "This Is some Normalized TEXT"
sample_small = lower_order(sample_text)
print(sample_small)

this is some normalized text

**Token Generation**

In [10]:
import nltk
nltk.download('punkt')
from nltk import word_tokenize

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.

In [11]:
from nltk.stem import WordNetLemmatizer
from nltk import word_tokenize,pos_tag
nltk.download('averaged_perceptron_tagger')
nltk.download('wordnet')

def lemmatization(token_text):
  """
  This function performs the lemmatization operations as explained above.
  Input Args:
  token_text: list of tokens.
  Returns:
  lemmatized_tokens: list of lemmatized tokens.
  """
  lemma_tokens = []
  wordnet = WordNetLemmatizer()
  lemmatized_tokens = [wordnet.lemmatize(token, pos = 'v') for token in token_text]

  return lemmatized_tokens

[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /root/nltk_data...
[nltk_data]   Unzipping taggers/averaged_perceptron_tagger.zip.
[nltk_data] Downloading package wordnet to /root/nltk_data...

In [12]:
nltk.download('stopwords')
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
stop_words = set(stopwords.words('english'))
custom_stopwords = ['@', 'RT']
stop_words.update(custom_stopwords)

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.

In [13]:

def remove_stopwords(text_tokens):
  """
  This function removes all the stopwords present in out text tokens.
  Input Args:
  text_tokens: tokenize input of our datasets.
  Returns:
  result_tokens: list of token without stopword.
  """

  result_tokens = []
  for token in text_tokens:
    if token not in stop_words:
       result_tokens.append(token)
  return result_tokens

In [14]:
from nltk.stem import PorterStemmer

def stemming(text):
  """
  This function performs stemming operations.
  Input Args:
  token_text: list of tokenize text.
  Returns:
  stemm_tokes: list of stemmed tokens.
  """
  porter = PorterStemmer()
  stemm_tokens = []
  for word in text:
    stemm_tokens.append(porter.stem(word))
  return stemm_tokens

In [15]:
from nltk.tokenize import RegexpTokenizer

from nltk.tokenize import RegexpTokenizer

def remove_punct(text):
  """
  This function removes the punctutations present in our text data.
  Input Args:
  text: text data.
  Returns:
  text: cleaned text.
  """
  tokenizer = RegexpTokenizer(r"\w+")
  lst=tokenizer.tokenize(' '.join(text))
  return lst

In [16]:
def text_cleaning_pipeline(dataset, rule="lemmatize"):
    """
    This function applies all text cleaning steps to the input dataset.
    Input Args:
      dataset: A string of text to be cleaned.
      rule: "lemmatize" or "stem" — controls the normalization method.
    Returns:
      A cleaned string of text.
    """
    # Convert the input to small/lower order
    data = lower_order(dataset)

    # Remove URLs
    data = remove_urls(data)

    # Remove emojis
    data = remove_emoji(data)

    # Remove all other unwanted characters
    data = removeunwanted_characters(data)

    # Create tokens
    tokens = data.split()

    # Remove stopwords
    tokens = remove_stopwords(tokens)

    if rule == "lemmatize":
        tokens = lemmatization(tokens)
    elif rule == "stem":
        tokens = stemming(tokens)
    else:
        print("Pick between lemmatize or stem")

    return " ".join(tokens)

In [17]:
test = data_text[0]

In [18]:
print(text_cleaning_pipeline(test))

sure tune watch donald trump late night david letterman present top ten list tonight

In [22]:
cleaned_text = data_text.apply(lambda dataset: text_cleaning_pipeline(dataset))

In [20]:
cleaned_text.head(20)

0     sure tune watch donald trump late night david ...
1     donald trump appear view tomorrow morning disc...
2     donald trump read top ten financial tip late s...
3     new blog post celebrity apprentice finale less...
4     persona never wallflowerid rather build wall c...
5     miss usa tara conner firedive always believer ...
6     listen interview donald trump discuss new book...
7     strive wholeness keep sense wonder intact dona...
8     enter think like champion sign book keychain c...
9         achiever achieve plateau begin donald j trump
10    dont afraid uniqueits like afraid best self do...
11         win live champion view moment donald j trump
12    dayswe could use little power trumpative think...
13    always know could precipice something great do...
14    read great interview donald trump appear new y...
15        keep fast short directwhatever donald j trump
16    dont forget enter think like champion sign boo...
17          know donald trump facebook become fan today
18    higher self direct opposition comfort zone don...
19      read excerpt think like champion donald j trump
Name: content, dtype: object

In [26]:
type(cleaned_text)

pandas.core.series.Series

In [28]:
tokens = cleaned_text.apply(lambda x: x.split())

In [31]:
tokens = cleaned_text.apply(str.split)
tokens.head(20)

0     [sure, tune, watch, donald, trump, late, night...
1     [donald, trump, appear, view, tomorrow, mornin...
2     [donald, trump, read, top, ten, financial, tip...
3     [new, blog, post, celebrity, apprentice, final...
4     [persona, never, wallflowerid, rather, build, ...
5     [miss, usa, tara, conner, firedive, always, be...
6     [listen, interview, donald, trump, discuss, ne...
7     [strive, wholeness, keep, sense, wonder, intac...
8     [enter, think, like, champion, sign, book, key...
9     [achiever, achieve, plateau, begin, donald, j,...
10    [dont, afraid, uniqueits, like, afraid, best, ...
11    [win, live, champion, view, moment, donald, j,...
12    [dayswe, could, use, little, power, trumpative...
13    [always, know, could, precipice, something, gr...
14    [read, great, interview, donald, trump, appear...
15    [keep, fast, short, directwhatever, donald, j,...
16    [dont, forget, enter, think, like, champion, s...
17    [know, donald, trump, facebook, become, fan, t...
18    [higher, self, direct, opposition, comfort, zo...
19    [read, excerpt, think, like, champion, donald,...
Name: content, dtype: object

In [33]:
tokens_no_stop = tokens.apply(remove_stopwords)

In [34]:
tokens_lemma = tokens_no_stop.apply(lemmatization)

**TF-IDF**

In [35]:
final_text = tokens_lemma.apply(lambda x: " ".join(x))

In [36]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer(max_features=5000)
X_tfidf = tfidf.fit_transform(final_text)

In [37]:
from tensorflow.keras.preprocessing.text import Tokenizer

tokenizer = Tokenizer(num_words=5000, oov_token="<OOV>")
tokenizer.fit_on_texts(final_text)

sequences = tokenizer.texts_to_sequences(final_text)

In [39]:
print(sequences[:5])

[[244, 421, 50, 14, 3, 679, 88, 619, 1187, 983, 231, 1892, 722, 79], [14, 3, 1745, 504, 163, 215, 233, 290, 149, 13, 147, 37, 17, 404], [14, 3, 166, 231, 1892, 930, 1854, 679, 44, 619, 1187, 972], [13, 2676, 388, 290, 149, 1893, 2507, 393, 518, 64], [4587, 30, 1, 680, 100, 146, 1, 14, 531, 3]]

In [40]:
print(tokenizer.word_index)

{'<OOV>': 1, 'great': 2, 'trump': 3, 'thank': 4, 'get': 5, 'make': 6, 'president': 7, 'go': 8, 'people': 9, 'us': 10, 'would': 11, 'time': 12, 'new': 13, 'donald': 14, 'say': 15, 'country': 16, 'like': 17, 'run': 18, 'america': 19, 'job': 20, 'good': 21, 'need': 22, 'big': 23, 'look': 24, 'want': 25, 'one': 26, 'dont': 27, 'vote': 28, 'obama': 29, 'never': 30, 'work': 31, 'love': 32, 'many': 33, 'know': 34, 'state': 35, 'see': 36, 'think': 37, 'realdonaldtrump': 38, 'much': 39, 'take': 40, 'back': 41, 'win': 42, 'give': 43, 'show': 44, 'news': 45, 'come': 46, 'best': 47, 'even': 48, 'deal': 49, 'watch': 50, 'today': 51, 'must': 52, 'democrats': 53, 'really': 54, 'border': 55, 'last': 56, 'years': 57, 'interview': 58, 'true': 59, 'cant': 60, 'bad': 61, 'hillary': 62, 'china': 63, 'way': 64, 'american': 65, 'ever': 66, 'day': 67, 'keep': 68, 'right': 69, 'fake': 70, 'world': 71, 'first': 72, 'poll': 73, 'call': 74, 'better': 75, 'media': 76, 'nothing': 77, 'im': 78, 'tonight': 79, 'unite': 80, 'talk': 81, 'well': 82, 'tax': 83, 'always': 84, 'mr': 85, 'house': 86, 'please': 87, 'night': 88, 'let': 89, 'start': 90, 'stop': 91, 'use': 92, 'record': 93, 'pay': 94, 'money': 95, 'amaze': 96, 'man': 97, 'leave': 98, 'real': 99, 'build': 100, 'hard': 101, 'year': 102, 'election': 103, 'cont': 104, 'campaign': 105, 'lose': 106, 'report': 107, 'tell': 108, 'national': 109, 'forward': 110, 'nice': 111, 'help': 112, 'could': 113, 'live': 114, 'meet': 115, 'happen': 116, '2016': 117, 'total': 118, 'also': 119, 'republican': 120, 'golf': 121, 'another': 122, 'business': 123, 'clinton': 124, 'honor': 125, 'support': 126, 'believe': 127, 'trade': 128, 'happy': 129, 'next': 130, 'youre': 131, 'speak': 132, 'course': 133, 'fight': 134, 'two': 135, 'strong': 136, 'long': 137, 'agree': 138, 'number': 139, 'congratulations': 140, 'things': 141, 'doesnt': 142, 'republicans': 143, 'put': 144, 'far': 145, 'wall': 146, 'book': 147, 'bring': 148, 'apprentice': 149, 'try': 150, 'play': 151, 'hope': 152, 'every': 153, 'military': 154, 'economy': 155, 'change': 156, 'usa': 157, 'obamacare': 158, 'party': 159, 'spend': 160, 'wait': 161, 'everyone': 162, 'tomorrow': 163, 'hear': 164, 'place': 165, 'read': 166, 'history': 167, 'crook': 168, 'enjoy': 169, 'totally': 170, 'open': 171, 'ask': 172, 'debate': 173, 'dems': 174, 'wonderful': 175, 'interest': 176, 'soon': 177, 'didnt': 178, 'thats': 179, 'end': 180, 'miss': 181, 'continue': 182, 'fail': 183, 'guy': 184, 'success': 185, 'bill': 186, 'lie': 187, 'hes': 188, 'security': 189, 'north': 190, 'lead': 191, 'cut': 192, 'remember': 193, 'become': 194, 'lot': 195, 'beautiful': 196, 'york': 197, 'white': 198, 'smart': 199, 'pm': 200, 'sign': 201, 'fire': 202, 'crime': 203, 'fantastic': 204, 'wrong': 205, 'wow': 206, 'thing': 207, 'u': 208, 'attack': 209, 'respect': 210, 'hit': 211, 'office': 212, 'find': 213, 'russia': 214, 'morning': 215, 'iran': 216, 'allow': 217, 'plan': 218, 'congress': 219, 'word': 220, 'speech': 221, 'join': 222, 'witch': 223, 'stand': 224, 'story': 225, 'washington': 226, 'hunt': 227, 'together': 228, 'americans': 229, 'illegal': 230, 'top': 231, 'others': 232, 'discuss': 233, 'stay': 234, 'high': 235, 'kill': 236, 'dollars': 237, 'still': 238, 'terrible': 239, 'tough': 240, 'yesterday': 241, 'mexico': 242, 'crowd': 243, 'sure': 244, 'ratings': 245, 'presidential': 246, 'immigration': 247, 'care': 248, 'person': 249, 'buy': 250, 'john': 251, 'head': 252, 'release': 253, 'since': 254, 'wont': 255, 'government': 256, 'democrat': 257, 'include': 258, 'turn': 259, 'focus': 260, 'may': 261, 'season': 262, 'fact': 263, 'leader': 264, 'save': 265, 'without': 266, 'massive': 267, 'point': 268, 'already': 269, 'order': 270, 'life': 271, 'countries': 272, 'major': 273, 'important': 274, 'administration': 275, 'fix': 276, 'collusion': 277, 'florida': 278, 'sad': 279, 'week': 280, 'million': 281, 'move': 282, 'something': 283, 'anything': 284, 'name': 285, 'family': 286, 'senate': 287, 'greatest': 288, 'tweet': 289, 'celebrity': 290, 'proud': 291, 'tower': 292, 'gop': 293, 'close': 294, 'announce': 295, '2': 296, 'bush': 297, 'yes': 298, 'leadership': 299, 'truly': 300, 'political': 301, 'game': 302, 'wish': 303, 'korea': 304, 'protect': 305, 'price': 306, 'ill': 307, 'fbi': 308, 'law': 309, 'create': 310, 'fast': 311, 'everything': 312, 'home': 313, 'yet': 314, 'company': 315, 'entrepreneurs': 316, 'send': 317, 'obamas': 318, 'begin': 319, 'anyone': 320, 'disaster': 321, 'problem': 322, 'market': 323, 'cruz': 324, 'act': 325, 'team': 326, 'luck': 327, 'force': 328, 'away': 329, 'court': 330, 'beat': 331, 'dc': 332, 'leaders': 333, 'tremendous': 334, 'write': 335, 'nation': 336, 'iowa': 337, '4': 338, 'set': 339, 'energy': 340, 'around': 341, 'rally': 342, 'south': 343, 'ready': 344, 'case': 345, 'ive': 346, 'destroy': 347, 'successful': 348, 'governor': 349, 'waste': 350, 'someone': 351, 'isis': 352, 'pass': 353, 'question': 354, 'hotel': 355, 'billion': 356, 'excite': 357, 'reason': 358, 'little': 359, '3': 360, 'truth': 361, 'ago': 362, 'incredible': 363, 'special': 364, 'mueller': 365, '5': 366, 'war': 367, 'general': 368, 'full': 369, 'part': 370, 'old': 371, '100': 372, 'wind': 373, 'scotland': 374, 'worst': 375, 'almost': 376, 'future': 377, 'actually': 378, 'justice': 379, '10': 380, 'raise': 381, 'art': 382, 'candidate': 383, 'rat': 384, 'fox': 385, 'tariff': 386, 'senator': 387, 'post': 388, 'cnn': 389, 'complete': 390, 'millions': 391, 'carolina': 392, 'learn': 393, 'else': 394, 'endorsement': 395, 'impeachment': 396, 'badly': 397, 'press': 398, 'enough': 399, 'city': 400, 'low': 401, 'oil': 402, 'drug': 403, 'champion': 404, 'biggest': 405, 'vet': 406, 'check': 407, 'visit': 408, 'isnt': 409, 'break': 410, 'economic': 411, 'w': 412, 'birthday': 413, 'return': 414, 'mean': 415, 'forget': 416, 'nbc': 417, 'increase': 418, 'worse': 419, 'corrupt': 420, 'tune': 421, 'awesome': 422, 'women': 423, 'control': 424, 'power': 425, 'finally': 426, 'fan': 427, 'hold': 428, 'god': 429, 'phony': 430, 'result': 431, 'stock': 432, 'cannot': 433, 'despite': 434, 'weak': 435, 'dishonest': 436, 'follow': 437, 'listen': 438, 'cost': 439, 'tie': 440, 'days': 441, 'sell': 442, 'tv': 443, 'unemployment': 444, 'donaldtrump': 445, 'onfoxandfriends': 446, 'friends': 447, 'zero': 448, 'hell': 449, 'jeb': 450, 'debt': 451, 'victory': 452, 'host': 453, 'iraq': 454, 'second': 455, 'friend': 456, 'chance': 457, 'answer': 458, 'service': 459, 'chicago': 460, '1': 461, 'understand': 462, 'statement': 463, 'ohio': 464, 'free': 465, 'stupid': 466, 'ted': 467, 'club': 468, 'crazy': 469, 'feel': 470, 'base': 471, 'healthcare': 472, 'public': 473, 'offer': 474, 'highly': 475, 'nancy': 476, 'race': 477, 'radical': 478, 'mind': 479, 'hoax': 480, 'welcome': 481, 'action': 482, 'treat': 483, 'federal': 484, 'southern': 485, 'hand': 486, 'foreign': 487, 'level': 488, 'doral': 489, 'fair': 490, 'mess': 491, 'hate': 492, '9': 493, 'star': 494, 'twitter': 495, 'politicians': 496, 'problems': 497, 'prove': 498, 'international': 499, 'sunday': 500, 'politics': 501, 'shoot': 502, 'syria': 503, 'view': 504, 'highest': 505, 'wonder': 506, 'mark': 507, 'event': 508, 'past': 509, 'mistake': 510, 'less': 511, 'able': 512, 'rubio': 513, 'safe': 514, 'push': 515, 'joe': 516, 'absolutely': 517, 'along': 518, 'nuclear': 519, 'fun': 520, 'nobody': 521, 'pelosi': 522, 'decision': 523, 'billions': 524, 'nations': 525, 'matter': 526, 'immediately': 527, 'easy': 528, 'die': 529, 'charge': 530, 'j': 531, 'nyc': 532, 'face': 533, 'drop': 534, 'global': 535, 'longer': 536, 'system': 537, 'monday': 538, 'fall': 539, 'via': 540, 'winner': 541, 'issue': 542, 'rise': 543, 'americas': 544, 'comey': 545, 'cover': 546, 'laugh': 547, 'large': 548, 'award': 549, 'fee': 550, 'russian': 551, 'laws': 552, 'side': 553, 'seem': 554, 'surprise': 555, 'rule': 556, 'primary': 557, 'texas': 558, 'judge': 559, 'congrats': 560, 'class': 561, 'bless': 562, 'thousands': 563, 'receive': 564, 'perhaps': 565, 'small': 566, 'warm': 567, 'email': 568, 'promise': 569, 'id': 570, 'favorite': 571, 'horrible': 572, 'term': 573, 'elect': 574, 'possible': 575, 'whats': 576, 'onfoxnews': 577, 'correct': 578, 'jam': 579, 'refuse': 580, 'families': 581, 'consider': 582, 'angry': 583, 'air': 584, 'west': 585, 'melania': 586, 'policy': 587, 'pennsylvania': 588, 'catch': 589, 'israel': 590, 'rate': 591, 'false': 592, 'amendment': 593, 'cause': 594, 'schiff': 595, 'thoughts': 596, 'concern': 597, 'hurt': 598, 'young': 599, 'early': 600, 'choice': 601, 'veterans': 602, 'men': 603, 'california': 604, 'stories': 605, 'prime': 606, 'weekend': 607, 'vegas': 608, 'touch': 609, 'information': 610, 'sir': 611, '2nd': 612, 'bernie': 613, 'saw': 614, 'gun': 615, 'virginia': 616, 'dumb': 617, 'apologize': 618, 'david': 619, 'hampshire': 620, 'losers': 621, 'video': 622, 'line': 623, 'negotiate': 624, 'fully': 625, 'least': 626, 'loser': 627, 'enforcement': 628, 'deliver': 629, 'mike': 630, 'secretary': 631, 'deserve': 632, 'november': 633, '8': 634, 'article': 635, 'investigation': 636, 'ridiculous': 637, '7': 638, 'supporters': 639, 'whole': 640, 'supreme': 641, 'expect': 642, 'barackobama': 643, 'maybe': 644, 'instead': 645, 'mention': 646, 'room': 647, 'group': 648, 'remain': 649, 'saturday': 650, 'ny': 651, 'entire': 652, 'credit': 653, 'pick': 654, 'serve': 655, 'rig': 656, 'approval': 657, 'tuesday': 658, 'r': 659, 'conference': 660, 'school': 661, 'unfair': 662, 'haters': 663, 'sense': 664, 'romney': 665, '50': 666, 'scam': 667, 'michael': 668, 'wife': 669, 'theyre': 670, 'demand': 671, 'youve': 672, 'months': 673, 'idea': 674, 'voters': 675, '12': 676, 'former': 677, 'dead': 678, 'late': 679, 'rather': 680, 'comment': 681, 'budget': 682, 'bob': 683, 'couldnt': 684, 'middle': 685, 'especially': 686, 'march': 687, 'huge': 688, 'wouldnt': 689, 'growth': 690, 'admit': 691, 'lower': 692, 'land': 693, 'candidates': 694, 'las': 695, 'charity': 696, 'appreciate': 697, 'approve': 698, 'chinese': 699, 'sorry': 700, 'dangerous': 701, 'dream': 702, 'convention': 703, 'chris': 704, 'police': 705, 'workers': 706, 'gas': 707, 'bore': 708, 'negative': 709, 'bigger': 710, 'quickly': 711, 'farmers': 712, 'higher': 713, 'hopefully': 714, 'worth': 715, 'canada': 716, 'final': 717, 'robert': 718, 'fund': 719, 'spy': 720, 'everybody': 721, 'list': 722, 'terrific': 723, 'weeks': 724, 'children': 725, 'celebrate': 726, 'chuck': 727, 'disgrace': 728, 'probably': 729, 'represent': 730, 'defense': 731, 'mitt': 732, 'though': 733, 'review': 734, 'ukraine': 735, 'television': 736, 'intelligence': 737, 'source': 738, 'page': 739, 'kind': 740, 'positive': 741, 'blue': 742, 'blow': 743, 'joke': 744, 'etc': 745, 'fraud': 746, 'pres': 747, 'link': 748, 'finish': 749, 'dollar': 750, 'glad': 751, 'bias': 752, 'freedom': 753, 'center': 754, 'defend': 755, 'potus': 756, 'add': 757, 'sound': 758, 'kim': 759, 'experience': 760, 'rebuild': 761, 'presidency': 762, 'safety': 763, 'minister': 764, 'ebola': 765, 'obstruction': 766, 'father': 767, 'policies': 768, 'claim': 769, 'reagan': 770, 'wasnt': 771, 'perfect': 772, 'process': 773, 'advice': 774, 'beach': 775, 'brand': 776, 'grow': 777, 'members': 778, 'except': 779, 'potential': 780, 'message': 781, 'sit': 782, 'theres': 783, 'paul': 784, 'enemy': 785, 'hat': 786, 'across': 787, '18': 788, 'doubt': 789, 'adam': 790, 'magazine': 791, 'macys': 792, 'congressman': 793, '2012': 794, 'worry': 795, 'three': 796, 'turbines': 797, 'lowest': 798, 'inspire': 799, 'fool': 800, 'drive': 801, 'handle': 802, 'phone': 803, 'thx': 804, 'hours': 805, 'eric': 806, 'four': 807, 'project': 808, 'failure': 809, 'trust': 810, 'ahead': 811, 'street': 812, 'george': 813, 'death': 814, 'stronger': 815, 'thewhitehouse': 816, 'minutes': 817, 'putin': 818, 'rest': 819, 'step': 820, 'feature': 821, 'cast': 822, 'todays': 823, 'staff': 824, 'christmas': 825, 'behind': 826, 'historic': 827, 'reform': 828, 'marco': 829, 'universe': 830, 'episode': 831, 'front': 832, '15': 833, 'serious': 834, 'sue': 835, 'woman': 836, '700': 837, 'mayor': 838, 'facts': 839, '2020': 840, 'picture': 841, 'committee': 842, 'endorse': 843, 'explain': 844, 'pathetic': 845, 'college': 846, 'ads': 847, '13': 848, 'either': 849, 'alabama': 850, 'progress': 851, 'dinner': 852, 'brave': 853, 'due': 854, 'prepare': 855, 'poor': 856, 'talent': 857, 'wisconsin': 858, 'lawyer': 859, 'confidence': 860, 'short': 861, 'university': 862, 'friday': 863, 'rich': 864, 'steal': 865, 'super': 866, '20': 867, 'japan': 868, 'whistleblower': 869, 'powerful': 870, '16': 871, '25': 872, 'pressure': 873, 'sadly': 874, 'situation': 875, 'arent': 876, 'son': 877, 'michigan': 878, 'easily': 879, 'ice': 880, 'carson': 881, 'turnberry': 882, 'impeach': 883, 'pageant': 884, 'hurricane': 885, 'relationship': 886, 'department': 887, 'legal': 888, 'presidents': 889, 'afraid': 890, 'kid': 891, 'shes': 892, 'announcement': 893, 'career': 894, 'favor': 895, 'clean': 896, 'address': 897, 'realize': 898, 'wh': 899, 'excellent': 900, 'different': 901, 'lightweight': 902, 'secure': 903, 'andrew': 904, 'prayers': 905, 'opportunity': 906, '6': 907, 'amount': 908, 'food': 909, 'bank': 910, 'hall': 911, 'decide': 912, 'agenda': 913, 'forrealdonaldtrump': 914, 'miami': 915, 'scott': 916, 'arizona': 917, 'private': 918, 'solve': 919, 'incompetent': 920, 'east': 921, 'heart': 922, 'arrive': 923, 'leak': 924, 'sanders': 925, 'conflict': 926, 'water': 927, 'criminal': 928, 'ag': 929, 'financial': 930, 'youll': 931, 'un': 932, 'imagine': 933, 'involve': 934, 'brilliant': 935, 'illegally': 936, 'daca': 937, 'et': 938, 'reality': 939, 'month': 940, 'ad': 941, 'strength': 942, 'tom': 943, 'steve': 944, 'outside': 945, 'honest': 946, 'jeff': 947, 'attorney': 948, 'rock': 949, 'oh': 950, 'meetings': 951, 'strongly': 952, 'defeat': 953, 'whether': 954, 'field': 955, 'website': 956, 'politician': 957, 'failingnytimes': 958, 'ticket': 959, 'soldier': 960, 'trillion': 961, 'repeal': 962, 'fine': 963, 'manufacture': 964, 'crisis': 965, 'anymore': 966, '3rd': 967, 'anyway': 968, 'evidence': 969, '800': 970, 'nevada': 971, 'funny': 972, 'spectacular': 973, 'double': 974, 'movement': 975, 'statements': 976, 'ideas': 977, 'troop': 978, 'network': 979, 'credibility': 980, 'passion': 981, 'nato': 982, 'present': 983, 'plus': 984, 'businessman': 985, 'racist': 986, 'piece': 987, 'greatly': 988, 'third': 989, 'sometimes': 990, 'countrys': 991, 'liberal': 992, 'exactly': 993, 'gain': 994, 'investigate': 995, 'dnc': 996, 'often': 997, 'common': 998, 'director': 999, 'palm': 1000, 'king': 1001, 'response': 1002, 'socalled': 1003, 'terrorist': 1004, 'sleepy': 1005, 'estate': 1006, 'red': 1007, 'dan': 1008, 'subject': 1009, 'commit': 1010, 'travel': 1011, 'intl': 1012, 'player': 1013, 'tea': 1014, 'arm': 1015, '30': 1016, 'predict': 1017, 'request': 1018, 'form': 1019, 'accomplish': 1020, 'monster': 1021, 'resort': 1022, '1st': 1023, 'negotiation': 1024, 'france': 1025, 'decades': 1026, 'exist': 1027, 'heroes': 1028, 'amnesty': 1029, 'illegals': 1030, 'kevin': 1031, 'weve': 1032, 'trip': 1033, 'june': 1034, 'hire': 1035, 'five': 1036, 'rip': 1037, 'trouble': 1038, 'spirit': 1039, 'blame': 1040, 'majority': 1041, 'flag': 1042, 'gift': 1043, 'shirt': 1044, 'beyond': 1045, 'kick': 1046, 'turkey': 1047, 'model': 1048, 'summit': 1049, 'whatever': 1050, 'ifrealdonaldtrump': 1051, 'victims': 1052, 'schumer': 1053, 'park': 1054, 'definitely': 1055, 'chief': 1056, 'immigrants': 1057, 'hero': 1058, 'careful': 1059, 'quote': 1060, 'test': 1061, 'steel': 1062, 'inspiration': 1063, 'nfl': 1064, 'pour': 1065, 'dossier': 1066, 'collection': 1067, 'benefit': 1068, 'provide': 1069, 'popular': 1070, 'impact': 1071, 'letter': 1072, 'billionaire': 1073, 'dummy': 1074, 'myfoxandfriends': 1075, 'chairman': 1076, 'wear': 1077, '730': 1078, 'seriously': 1079, 'train': 1080, 'louisiana': 1081, 'lady': 1082, 'conversation': 1083, 'thursday': 1084, 'social': 1085, 'advantage': 1086, 'bear': 1087, 'sanction': 1088, 'replace': 1089, 'union': 1090, 'track': 1091, 'challenge': 1092, 'patrol': 1093, 'accord': 1094, 'county': 1095, 'peace': 1096, 'ass': 1097, 'ur': 1098, 'puerto': 1099, 'est': 1100, 'share': 1101, 'key': 1102, 'worlds': 1103, 'gang': 1104, 'sick': 1105, 'aid': 1106, 'currency': 1107, 'biden': 1108, 'havent': 1109, 'local': 1110, 'value': 1111, 'kelly': 1112, 'officer': 1113, 'certain': 1114, 'players': 1115, 'health': 1116, 'africa': 1117, 'human': 1118, 'role': 1119, 'storm': 1120, 'inform': 1121, 'rico': 1122, 'enter': 1123, 'walk': 1124, 'choose': 1125, '14': 1126, 'black': 1127, 'holiday': 1128, 'georgia': 1129, 'san': 1130, 'program': 1131, 'necessary': 1132, 'clear': 1133, 'ally': 1134, 'abuse': 1135, 'position': 1136, 'lucky': 1137, 'whose': 1138, 'guess': 1139, 'luxury': 1140, 'expose': 1141, 'suffer': 1142, 'board': 1143, 'ok': 1144, 'mrtrump': 1145, 'cool': 1146, 'ivanka': 1147, '1000': 1148, 'europe': 1149, 'reach': 1150, 'community': 1151, 'straight': 1152, 'later': 1153, 'al': 1154, 'simple': 1155, 'conservative': 1156, 'cancel': 1157, 'signature': 1158, 'secret': 1159, '900': 1160, 'design': 1161, 'disgust': 1162, 'courage': 1163, 'brian': 1164, 'shouldnt': 1165, 'crimes': 1166, 'dopey': 1167, 'recent': 1168, 'outstanding': 1169, 'accept': 1170, 'purchase': 1171, 'among': 1172, 'opec': 1173, 'citizens': 1174, 'clue': 1175, 'saudi': 1176, 'fly': 1177, 'delay': 1178, 'bet': 1179, 'insurance': 1180, 'mccain': 1181, 'coverage': 1182, 'pray': 1183, 'terrorists': 1184, 'agreement': 1185, 'genius': 1186, 'letterman': 1187, 'expand': 1188, 'card': 1189, 'effort': 1190, 'va': 1191, 'arod': 1192, '17': 1193, 'single': 1194, 'target': 1195, 'uk': 1196, 'barack': 1197, 'dem': 1198, 'bomb': 1199, 'rid': 1200, 'peter': 1201, 'benghazi': 1202, 'flight': 1203, 'clintons': 1204, 'corruption': 1205, 'kasich': 1206, 'pack': 1207, 'desperate': 1208, 'negotiations': 1209, 'deficit': 1210, 'innocent': 1211, 'vision': 1212, 'copy': 1213, 'maralago': 1214, 'paper': 1215, 'hi': 1216, 'momentum': 1217, 'stuff': 1218, 'ban': 1219, 'quit': 1220, 'hotels': 1221, 'boss': 1222, 'recently': 1223, 'threat': 1224, 'chinas': 1225, 'stick': 1226, 'green': 1227, 'completely': 1228, 'mine': 1229, 'beg': 1230, 'might': 1231, 'mittromney': 1232, 'vp': 1233, 'ford': 1234, 'opponent': 1235, 'indiana': 1236, 'matt': 1237, 'anybody': 1238, 'officials': 1239, 'shutdown': 1240, 'desperately': 1241, 'nights': 1242, 'mexican': 1243, 'tour': 1244, 'hack': 1245, 'executive': 1246, 'talented': 1247, 'jim': 1248, 'restore': 1249, 'eye': 1250, 'xi': 1251, 'fortune': 1252, 'germany': 1253, 'scandal': 1254, 'partner': 1255, 'launch': 1256, 'hour': 1257, 'study': 1258, 'greater': 1259, 'rove': 1260, 'businesses': 1261, 'enemies': 1262, 'b': 1263, 'file': 1264, 'alone': 1265, 'shut': 1266, 'establishment': 1267, 'excuse': 1268, 'notice': 1269, 'reserve': 1270, 'cities': 1271, 'trial': 1272, 'climate': 1273, 'near': 1274, 'expensive': 1275, 'kentucky': 1276, 'loss': 1277, 'gold': 1278, 'anniversary': 1279, 'fame': 1280, 'hundreds': 1281, 'weapons': 1282, 'seek': 1283, 'prez': 1284, 'ones': 1285, 'damage': 1286, 'jon': 1287, 'behalf': 1288, 'sc': 1289, 'opinion': 1290, 'farm': 1291, 'testify': 1292, 'senators': 1293, 'jong': 1294, 'joan': 1295, 'roll': 1296, 'anywhere': 1297, 'aberdeen': 1298, 'current': 1299, 'solution': 1300, 'ruin': 1301, 'figure': 1302, 'property': 1303, 'account': 1304, 'warren': 1305, 'product': 1306, 'lawyers': 1307, 'standard': 1308, 'witness': 1309, 'greta': 1310, 'schedule': 1311, '11': 1312, 'afternoon': 1313, 'january': 1314, 'events': 1315, 'regard': 1316, 'anthony': 1317, 'within': 1318, 'closely': 1319, 'legislation': 1320, 'succeed': 1321, 'wealth': 1322, 'reveal': 1323, 'hide': 1324, 'plant': 1325, 'carter': 1326, 'boardroom': 1327, 'light': 1328, 'lyin': 1329, 'district': 1330, 'transcript': 1331, 'winners': 1332, 'central': 1333, 'foundation': 1334, 'speaker': 1335, 'owe': 1336, 'grand': 1337, 'unbelievable': 1338, 're

In [41]:
from tensorflow.keras.preprocessing.sequence import pad_sequences

X = pad_sequences(
    sequences,
    maxlen=50,
    padding='post',
    truncating='post'
)

print(X.shape)

(41122, 50)